title: Jordan Ellison
author: Pava
email: jellison8640@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first website. 
  To show that I can code

# social links
twitter_username: j_ellison10 # DO NOT include the @ character, or else the build will fail!
github_username:  jellison8640 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
toc: TRUE
toc_float: TRUE
highlight: breezedark
